import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Manrope,
  Open_Sans,
  Poppins,
} from "next/font/google";
import "./globals.css";

const heading = Poppins({
  variable: "--heading",
  subsets: ["latin"],
  weight: ["500", "300", "700"],
});

const paragraph = Manrope({
  variable: "--paragraph",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${heading.variable} ${paragraph.variable} antialiased w-screen min-h-screen relative`}
      >
        {children}
      </body>
    </html>
  );
}
